spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=nammon
spring.datasource.password=14092545

# ตั้งค่าให้ hibernate สร้าง table ให้อัตโนมัติจาก Entity (@Entity)
spring.jpa.hibernate.ddl-auto=update

# แสดง sql query ใน terminal ด้วย
spring.jpa.show-sql=true

# ปรับ format sql query ให้อ่านง่าย
spring.jpa.properties.hibernate.format_sql=true